# Generated by Django 4.2 on 2023-06-24 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mp4_file', models.CharField(max_length=255)),
                ('vtt_file', models.CharField(max_length=255)),
                ('gif_file', models.CharField(max_length=255)),
                ('thumbnail_file', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Videoprocess',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
