# Generated by Django 4.2 on 2023-06-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0001_initial'),
    ]

    operations = [
    ]
