# Generated by Django 4.2 on 2023-06-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0002_auto_20230624_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uuid',
        ),
    ]
