#version: "3"
#services:
#  app:
#    restart: always
#    build: .
#    command: "python3 manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
version: "3"
services:
  app:
    restart: always
    build: .
    command: >
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:  # Add environment variables here
      MINIO_ENDPOINT: "console.minio.mk8snode4.hhii.ampere"
      MINIO_ACCESS_KEY: "BrX27xJJZPtwP90vYCC7"
      MINIO_SECRET_KEY: "E3KDljYLLDsIaiije4dw6PLa9VXYBsWYi9b945vH"
      MINIO_BUCKET_NAME: "vpp-dst"
      DJANGO_ALLOWED_HOSTS: "demo.mk8snode4.hhii.ampere,10.77.123.232,127.0.0.1"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      DB_HOST: "10.77.123.232"
      DB_PORT: "30312"
