FROM python:3.10-slim-bullseye
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code

RUN pip install pip -U

ADD requirements.txt /code/

RUN pip install -r requirements.txt

#ADD . /code/
COPY manage.py /
COPY vod_db /
COPY media /code/
COPY static /code/
COPY videoplayer /code/
COPY vod_backend /code/
