apiVersion: v1
kind: Pod
metadata:
  name: vpp-app-f623f225-9658-4719-86a1-e113bb28508e
  labels:
    app: vpp-app-f623f225-9658-4719-86a1-e113bb28508e
spec:
  volumes:
  - name: credentials
    configMap:
      name: miniocredentials
  containers:
  - name: vpp-app1
    image: docker.io/mrdojojo/video-processor-ffmpeg:1.2
    env:
    - name: ENDPOINT_URL
      value: "http://console.minio.mk8snode4.hhii.ampere/"
    - name: SRC_OBJECT_KEY
      value: "Ampere_CIDR.mp4"
    - name: SRC_S3_BUCKET
      value: "vod-poc"
    - name: SRC_S3_REGION
      value: ""
    - name: DST_S3_REGION
      value: ""
    - name: DST_S3_BUCKET
      value: "vpp-dst"
    resources:
      limits:
        cpu: "20"
      requests:
        cpu: "15"
    volumeMounts:
    - name: credentials
      readOnly: true
      mountPath: "/home/altrauser/.aws/credentials"
      subPath: credentials
  restartPolicy: OnFailure
   